  # name: Nookhub
  # user: abhi
  # password: Abhi1234@
  # host: localhost
  # port: 5433

  name: postgres
  user: postgres.gklzzvhfvzhzjuwokizq
  password: Nookhub@1234
  host: aws-0-ap-south-1.pooler.supabase.com
  port: 6543
